ALTER TABLE `#__fabrik_connections` MODIFY `description` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_connections` MODIFY `checked_out_time` DATETIME DEFAULT NULL

ALTER TABLE `#__fabrik_cron` MODIFY `label` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_cron` MODIFY `frequency` SMALLINT(6) DEFAULT 0
ALTER TABLE `#__fabrik_cron` MODIFY `unit` VARCHAR(15) DEFAULT ''
ALTER TABLE `#__fabrik_cron` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_cron` MODIFY `created_by` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_cron` MODIFY `created_by_alias` VARCHAR(30) DEFAULT ''
ALTER TABLE `#__fabrik_cron` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_cron` MODIFY `modified_by` VARCHAR(30) DEFAULT ''
ALTER TABLE `#__fabrik_cron` MODIFY `checked_out` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_cron` MODIFY `checked_out_time` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_cron` MODIFY `published` TINYINT(1) DEFAULT 0
ALTER TABLE `#__fabrik_cron` MODIFY `plugin` VARCHAR(50) DEFAULT ''
ALTER TABLE `#__fabrik_cron` MODIFY `lastrun` DATETIME DEFAULT NULL

ALTER TABLE `#__fabrik_elements` MODIFY `group_id` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `checked_out` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `checked_out_time` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_elements` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_elements` MODIFY `created_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `created_by_alias` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_elements` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_elements` MODIFY `modified_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `width` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `hidden` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `eval` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `ordering` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `show_in_list_summary` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `filter_type` VARCHAR(20) DEFAULT ''
ALTER TABLE `#__fabrik_elements` MODIFY `filter_exact_match` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_elements` MODIFY `parent_id` MEDIUMINT(6) DEFAULT 0

ALTER TABLE `#__fabrik_formgroup` MODIFY `form_id` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_formgroup` MODIFY `group_id` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_formgroup` MODIFY `ordering` INT(4) DEFAULT 0

ALTER TABLE `#__fabrik_forms` MODIFY `label` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `record_in_database` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_forms` MODIFY `error` VARCHAR(150) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_forms` MODIFY `created_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_forms` MODIFY `created_by_alias` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_forms` MODIFY `modified_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_forms` MODIFY `checked_out` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_forms` MODIFY `checked_out_time` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_forms` MODIFY `publish_up` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_forms` MODIFY `publish_down` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_forms` MODIFY `reset_button_label` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `submit_button_label` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `form_template` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_forms` MODIFY `view_only_template` VARCHAR(255) DEFAULT ''

ALTER TABLE `#__fabrik_form_sessions` MODIFY `hash` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_form_sessions` MODIFY `user_id` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_form_sessions` MODIFY `form_id` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_form_sessions` MODIFY `row_id` INT(10) DEFAULT 0
ALTER TABLE `#__fabrik_form_sessions` MODIFY `last_page` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_form_sessions` MODIFY `referring_url` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_form_sessions` MODIFY `time_date` TIMESTAMP DEFAULT 0

ALTER TABLE `#__fabrik_groups` MODIFY `label` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_groups` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_groups` MODIFY `created_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_groups` MODIFY `created_by_alias` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_groups` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_groups` MODIFY `modified_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_groups` MODIFY `checked_out` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_groups` MODIFY `checked_out_time` DATETIME DEFAULT NULL

ALTER TABLE `#__fabrik_joins` MODIFY `list_id` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_joins` MODIFY `element_id` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_joins` MODIFY `join_from_table` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_joins` MODIFY `table_join` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_joins` MODIFY `table_key` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_joins` MODIFY `table_join_key` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_joins` MODIFY `join_type` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_joins` MODIFY `group_id` INT(10) DEFAULT 0

ALTER TABLE `#__fabrik_jsactions` MODIFY `element_id` INT(10) DEFAULT 0
ALTER TABLE `#__fabrik_jsactions` MODIFY `action` VARCHAR(255) DEFAULT ''

ALTER TABLE `#__fabrik_lists` MODIFY `label` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `form_id` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `db_table_name` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `db_primary_key` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `auto_inc` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `connection_id` INT(6) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_lists` MODIFY `created_by` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `created_by_alias` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_lists` MODIFY `modified_by` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `checked_out` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `checked_out_time` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_lists` MODIFY `publish_up` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_lists` MODIFY `publish_down` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_lists` MODIFY `access` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `hits` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `rows_per_page` INT(5) DEFAULT 0
ALTER TABLE `#__fabrik_lists` MODIFY `template` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `order_by` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `filter_action` VARCHAR(30) DEFAULT ''
ALTER TABLE `#__fabrik_lists` MODIFY `group_by` VARCHAR(255) DEFAULT ''

ALTER TABLE `#__fabrik_log` MODIFY `flag` SMALLINT(3) DEFAULT 0
ALTER TABLE `#__fabrik_log` MODIFY `referring_url` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_log` MODIFY `message_source` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_log` MODIFY `message_type` CHAR(60) DEFAULT ''

ALTER TABLE `#__fabrik_validations` MODIFY `element_id` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_validations` MODIFY `validation_plugin` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_validations` MODIFY `message` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_validations` MODIFY `checked_out` INT(4) DEFAULT 0
ALTER TABLE `#__fabrik_validations` MODIFY `checked_out_time` DATETIME DEFAULT NULL

ALTER TABLE `#__fabrik_visualizations` MODIFY `plugin` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_visualizations` MODIFY `label` VARCHAR(255) DEFAULT ''
ALTER TABLE `#__fabrik_visualizations` MODIFY `created` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_visualizations` MODIFY `created_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_visualizations` MODIFY `created_by_alias` VARCHAR(100) DEFAULT ''
ALTER TABLE `#__fabrik_visualizations` MODIFY `modified` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_visualizations` MODIFY `modified_by` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_visualizations` MODIFY `checked_out` INT(11) DEFAULT 0
ALTER TABLE `#__fabrik_visualizations` MODIFY `checked_out_time` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_visualizations` MODIFY `publish_up` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_visualizations` MODIFY `publish_down` DATETIME DEFAULT NULL
ALTER TABLE `#__fabrik_visualizations` MODIFY `published` INT(1) DEFAULT 0
ALTER TABLE `#__fabrik_visualizations` MODIFY `access` INT(6) DEFAULT 0